version: '2.1'

services:

  yeelight:
    build:
      context: ./
    restart: always
      command: -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005 ./app.jar
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2/repository/ie/daithi/yeelight/plex-webhook-yeelight/1.0.0-SNAPSHOT/plex-webhook-yeelight-1.0.0-SNAPSHOT.jar:/opt/app/app.jar